# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_leg_controller
    - right_leg_controller
    - total_controller

  left_leg_controller:
    type: FollowJointTrajectory
    joints:
      - left_motor_left_shoulder--left_motor
      - left_shoulder_left_top_leg-left_shoulder
      - left_top_leg_left_bottom_leg-left_top_leg
      - left_bottom_leg_left_foot-left_bottom_leg
    action_ns: follow_joint_trajectory
    default: true

  right_leg_controller:
    type: FollowJointTrajectory
    joints:
      - right_motor_right_shoulder-right_motor
      - right_shoulder_right_top_leg-right_shoulder
      - right_top_leg_right_bottom_leg--right_top_leg
      - right_bottom_leg_right_foot-right_bottom_leg
    action_ns: follow_joint_trajectory
    default: true

  total_controller:
    type: FollowJointTrajectory
    joints:
      - left_motor_left_shoulder--left_motor
      - left_shoulder_left_top_leg-left_shoulder
      - left_top_leg_left_bottom_leg-left_top_leg
      - left_bottom_leg_left_foot-left_bottom_leg
      - right_motor_right_shoulder-right_motor
      - right_shoulder_right_top_leg-right_shoulder
      - right_top_leg_right_bottom_leg--right_top_leg
      - right_bottom_leg_right_foot-right_bottom_leg
    action_ns: follow_joint_trajectory
    default: true